_target_: src.models.vaub_gp_module_fairface.VAUBGPModule

optimizer_vae_1:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 0.01

optimizer_vae_2:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 0.01

optimizer_score:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-3
  weight_decay: 0.01

optimizer_cls1:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 0.01

optimizer_cls2:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 0.01

#scheduler:
#  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#  _partial_: true
#  mode: min
#  factor: 0.1
#  patience: 10

vae1:
  _target_: src.models.components.vae_face.ResConvVAE
  logvar_constraint: "clamp"
  channel_size: 64
  _partial_: true

vae2:
  _target_: src.models.components.vae_face.ResConvVAE
  logvar_constraint: "clamp"
  channel_size: 64
  _partial_: true

score_prior:
  _target_: src.models.components.score_based_model.Score_fn_noise
  _partial_: true
  sigma_min: 0.01
  sigma_max: 1
  num_timesteps: 100
  is_add_latent_noise: false

unet:
  _target_: src.models.components.unet.CNNAdvancedUNet
  _partial_: true
  in_channels: 64
  num_timesteps: 100
  ch_multi: 2

classifier1:
  _target_: src.models.components.classifier_net.CustomClassifier
  num_classes: 7 
  _partial_: true

classifier2:
  _target_: src.models.components.classifier_net.CustomClassifier
  num_classes: 9
  _partial_: true

gp:
  _target_: src.models.components.gp_precomputed_model.GPModule
  _partial_: true
  diff: "MAE"
  mode: "max"
  dist_x_mode: "L22"
  threshold_0: 0.34
  threshold_1: 0.45
  coef_0: 9.2267
  intercept_0: -3.5454
  coef_1: 8.3527
  intercept_1: -4.2484


vaub_lambda: 1
gp_lambda: 0.00
recon_lambda: 10
var_lambda: 0.02

min_noise_scale: 0
max_noise_scale: 0
num_latent_noise_scale: 1
init_scale: 0.02

latent_dim: 1024
latent_row_dim: 16
latent_col_dim: 16

block_size: 800
cls_lambda: 1e-3
is_vanilla: true
loops: 1
warm_score_epochs: 0
gather_z: false
is_MoG_prior: False
is_warm_init: False

# compile model for faster training with pytorch 2.0
compile: false